import type { Metadata } from "next";
import Link from "next/link";

// Terms of service for the hosted (cloud) product. Plain and honest, same
// register as /privacy. Linked from checkout, the billing page, and the
// footer. Self-hosters run their own instance under AGPL and aren't bound by
// these commercial terms - only the dispatchseo.com service is.
//
// TWO THINGS TO KNOW BEFORE EDITING.
//
// 1. The risk clauses are structured, not just worded. The unlimited-liability
//    carve-out comes BEFORE the cap and lives in its own clause, and the cap is
//    a separate sentence from the exclusions. That is deliberate: under the
//    reasonableness tests courts apply to non-negotiated terms, a clause that
//    fails is struck out whole, and liability for that head of claim becomes
//    UNCAPPED. Splitting them means one failure doesn't take the rest down.
//    Don't merge them back into one tidy paragraph.
//
// 2. The cap is 12 months of fees with a floor, not 3 months. A cap set
//    conspicuously low is the kind courts refuse to enforce at all - and an
//    unenforceable low cap is worth less than an enforceable higher one.
//
// The service description must stay TRUE, including about automatic mode. A
// terms page that says the customer reviews everything, next to a product that
// can publish without review, hands away the exact allocation of
// responsibility this document exists to establish.

export const metadata: Metadata = {
  title: "Terms of service - DispatchSEO",
  description: "The terms for using the hosted DispatchSEO service at dispatchseo.com.",
};

const EFFECTIVE = "August 2, 2026";
const CONTACT = "support@dispatchseo.com";

// Must be the operator's full legal name, matching /privacy. A contract with
// an unnamed counterparty is a weak contract.
const OPERATOR = "Neo Zino";

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="space-y-3 text-sm leading-relaxed">
      <h2 className="text-lg font-medium text-white">{title}</h2>
      {children}
    </section>
  );
}

function Term({ children }: { children: React.ReactNode }) {
  return <strong className="text-neutral-100">{children}</strong>;
}

export default function TermsPage() {
  return (
    <main className="mx-auto max-w-2xl space-y-8 px-6 py-16 text-neutral-300">
      <div className="space-y-2">
        <h1 className="text-3xl font-semibold tracking-tight text-white">Terms of service</h1>
        <p className="text-sm text-neutral-500">Effective {EFFECTIVE}</p>
      </div>

      <Section title="Who you are contracting with">
        <p>
          These terms are an agreement between you and <Term>{OPERATOR}</Term>, an individual
          based in Israel operating the hosted DispatchSEO service at dispatchseo.com
          (&quot;we&quot;, &quot;us&quot;). By creating an account, subscribing, or using the
          hosted service, you agree to them. If you are agreeing on behalf of a company, you
          confirm you are authorised to bind it, and &quot;you&quot; means that company.
        </p>
        <p>
          DispatchSEO is also open source. If you self-host it, these commercial terms do not
          apply to you at all - your rights and obligations come from the AGPL-3.0 licence in
          the repository. These terms govern only the hosted service we run.
        </p>
      </Section>

      <Section title="The service">
        <p>
          DispatchSEO researches keywords for your website, drafts articles and interactive
          tools as pull requests to your repository, and tracks your search rankings. You
          connect your own GitHub repository, your own Google Search Console account, and your
          own coding-agent subscription. We provide the research data, the scheduling, the
          dashboard and the rank tracking.
        </p>
        <p>
          <Term>Content is generated by your coding-agent subscription, not by us.</Term> We
          orchestrate it; the drafting happens under your own account with a third-party
          provider, on their terms and at their cost.
        </p>
        <p>
          <Term>Review and automatic mode.</Term> By default every suggestion and every draft
          waits for you in a review queue, and nothing reaches your site until you approve it.
          You may also switch on automatic mode, which approves and merges on a schedule
          without waiting for you. <Term>If you enable automatic mode, content will be
          published to your site without your prior review, and you accept responsibility for
          it exactly as if you had approved each item yourself.</Term> Every change still
          arrives as a pull request in your own repository, so the record of what changed is
          yours and you can revert it. Automatic mode is off unless you turn it on.
        </p>
      </Section>

      <Section title="Your account">
        <p>
          You must be at least 18 to use the hosted service, and the information you sign up
          with must be accurate and kept up to date. You are responsible for keeping your
          sign-in method secure and for everything done under your account. Tell us promptly at{" "}
          {CONTACT} if you believe it has been compromised.
        </p>
        <p>
          Connect only websites and repositories you own or are authorised to manage, and only
          third-party accounts you are entitled to use. You are responsible for having the
          rights you assert when you connect something.
        </p>
      </Section>

      <Section title="Plans, billing, and renewal">
        <p>
          Paid plans are billed <Term>monthly in advance</Term> through our payment provider,
          Polar, who acts as merchant of record and is the seller of record for your purchase.
          Prices are shown at checkout. Each plan sets limits - number of sites and tracked
          keywords - which are enforced on your account.
        </p>
        <p>
          <Term>Your subscription renews automatically</Term> at the end of each billing period,
          at the then-current price, and your payment method is charged again, until you cancel.
          There is no minimum term.
        </p>
        <p>
          <Term>Free trial.</Term> Where a plan is offered with a free trial, the length of the
          trial is shown at checkout, your payment method is collected then, and it is first
          charged when the trial ends and the subscription begins. Cancel any time before the
          trial ends, from the billing page in your dashboard, and you are charged nothing.
        </p>
        <p>
          <Term>Cancelling.</Term> You can cancel at any time from the billing page in your
          dashboard - the same place and the same few clicks it took to subscribe. Cancellation
          takes effect at the end of the current billing period and you keep full access until
          then. We will never require you to email, call, or sit through a retention flow to
          cancel.
        </p>
        <p>
          <Term>Price changes.</Term> We may change prices. We will give you at least 30
          days&apos; notice by email before a new price applies to your subscription, and the
          change takes effect at your next renewal after that notice. If you don&apos;t want the
          new price, cancel before it takes effect; continuing to use the service after that is
          acceptance of it.
        </p>
        <p>
          <Term>Taxes.</Term> Prices exclude VAT and other applicable taxes unless stated
          otherwise. Polar handles tax collection and remittance as merchant of record.
        </p>
        <p>
          <Term>Failed payments.</Term> If a charge fails we may retry it and may suspend the
          service until payment succeeds. We will tell you before suspending.
        </p>
      </Section>

      <Section title="Refunds and your right to change your mind">
        <p>
          Outside the situations below, fees are non-refundable, including for partially used
          periods - cancelling stops future renewals rather than refunding the current one. If
          something went wrong on our side, contact us at {CONTACT} and we will sort it out
          case by case; we would rather refund you than argue.
        </p>
        <p>
          <Term>If you are a consumer in the EU, EEA or UK</Term> - meaning you are buying for
          purposes outside your trade, business or profession - you have a statutory right to
          withdraw from this contract within 14 days, without giving a reason. Because the
          service starts immediately, when you subscribe you expressly ask us to begin
          performance during that 14-day period and acknowledge that once we have fully
          performed you lose the right to withdraw. If you withdraw while the service is still
          running, you owe us a proportionate amount for what you have already received, and we
          refund the rest within 14 days using the same payment method. To withdraw, use the
          cancellation control on the billing page or write to {CONTACT} with a clear
          statement; we will confirm receipt in writing. Nothing in these terms takes away
          consumer rights that your local law does not let us take away.
        </p>
      </Section>

      <Section title="Acceptable use">
        <p>Use the service for your own websites and content. You must not:</p>
        <ul className="list-disc space-y-1 pl-5">
          <li>
            connect a site or repository you do not own or are not authorised to manage, or use
            someone else&apos;s credentials;
          </li>
          <li>
            generate or publish content that infringes anyone&apos;s copyright, trademark, or
            other rights, or that is defamatory, deceptive, or unlawful;
          </li>
          <li>
            run bulk or spam operations - mass-produced doorway pages, scaled content abuse, or
            anything designed primarily to manipulate search rankings rather than serve readers;
          </li>
          <li>
            abuse the connected APIs (Google Search Console, GitHub, DataForSEO, your coding
            agent) or breach their terms, or exceed the limits of your plan by technical means;
          </li>
          <li>
            attempt to access another customer&apos;s data, probe or interfere with the
            service&apos;s security, or use it to build a competing product from our
            non-public material;
          </li>
          <li>resell or provide the hosted service to third parties without our agreement.</li>
        </ul>
        <p>
          Security research is welcome if you tell us first at {CONTACT}, stay within your own
          account, and give us a reasonable chance to fix what you find before disclosing it.
        </p>
      </Section>

      <Section title="Your content, our service">
        <p>
          <Term>You own your content.</Term> Your site, your repository, the material you
          connect, and the pull requests generated for you remain yours. We claim no ownership
          of any of it. You grant us only the limited licence needed to operate the service for
          you - to store, process and transmit that material so the product can do the job you
          asked it to do - and that licence ends when you delete the material or your account.
        </p>
        <p>
          <Term>We own the service.</Term> DispatchSEO&apos;s hosted platform, its interfaces,
          and the DispatchSEO name and marks are ours. The software itself is licensed under
          AGPL-3.0, and those rights are what the licence grants you - nothing in these terms
          reduces them - but the licence does not give you a right to our trademarks or to the
          hosted service.
        </p>
        <p>
          <Term>Feedback.</Term> If you send us ideas or suggestions, we may use them freely
          and without obligation to you. We are not taking anything else you own by saying so.
        </p>
        <p>
          How we handle the data you connect is set out in our{" "}
          <Link className="text-white underline" href="/privacy">
            privacy policy
          </Link>
          . If you need a data processing agreement, ours is at{" "}
          <Link className="text-white underline" href="/dpa">
            /dpa
          </Link>
          .
        </p>
      </Section>

      <Section title="AI-generated content: what we do and do not promise">
        <p>
          The articles and tools this service produces are generated by AI. That carries risks
          which are inherent to the technology rather than defects we can engineer away, and
          you need to know what they are before you publish anything.
        </p>
        <p>
          <Term>Accuracy.</Term> AI output can be confidently wrong. It may contain factual
          errors, invented citations, outdated information, or claims about your own product
          that are not true. We do not warrant that any output is accurate, complete, or fit
          for any purpose. <Term>You must review output before publishing it</Term>, and if you
          have switched on automatic mode you have chosen to publish without that review and
          accepted the consequences.
        </p>
        <p>
          <Term>Originality and ownership.</Term> AI output may resemble existing material, and
          in many countries material generated without meaningful human authorship may not
          attract copyright at all. We assign to you whatever rights we may have in the output,
          <Term> if any</Term>, but we cannot and do not warrant that output is original, that
          it is protectable by copyright, or that publishing it will not infringe someone
          else&apos;s rights. Checking that is yours to do.
        </p>
        <p>
          <Term>Search results.</Term> SEO depends on many things outside anyone&apos;s control.
          We do not guarantee any ranking, any amount of traffic, that your pages will be
          indexed, or that they will not be affected by a search engine&apos;s algorithm
          changes, spam policies, or manual actions - including policies about AI-generated
          content, which change without notice. Nothing on our marketing pages is a promise of
          results.
        </p>
        <p>
          <Term>Your responsibility for what you publish.</Term> You decide what goes on your
          site. You are responsible for its accuracy, its legality, its compliance with the
          rules of the platforms it appears on, and for any labelling or disclosure your own
          law requires of AI-generated material.
        </p>
      </Section>

      <Section title="Third-party services">
        <p>
          The service works by connecting to accounts you bring: GitHub, Google Search Console,
          your coding-agent subscription (such as Anthropic&apos;s Claude or OpenAI&apos;s
          Codex), and optionally others such as DataForSEO. Your use of those services is
          governed by their own terms and paid for at their own prices. We are not responsible
          for their availability, their pricing, their output, or decisions they make about
          your accounts, and a failure or change on their side that degrades the service is not
          a breach of these terms by us. Payments are processed by Polar under Polar&apos;s own
          terms.
        </p>
      </Section>

      <Section title="Changes to the service">
        <p>
          We develop the product continuously and may add, change, or remove features. If we
          discontinue a material feature you are relying on, or the service as a whole, we will
          give you at least 30 days&apos; notice by email and refund any fees you have paid for
          a period you will not receive. Because the software is open source, discontinuation of
          the hosted service never leaves you without a way to keep running it.
        </p>
      </Section>

      <Section title="Suspension and termination">
        <p>
          You can cancel or delete your account at any time from the dashboard. Deleting your
          account cancels your subscription, removes DispatchSEO from your connected
          repositories, and erases your projects and their history.
        </p>
        <p>
          We may suspend or terminate an account that breaches these terms, abuses the service
          or the connected APIs, or creates legal or security risk for us or other customers.
          We will give notice and a chance to fix the problem where it is reasonable to do so;
          where the risk is serious or ongoing we may act first and explain immediately after.
          If we terminate you without cause, we refund the unused portion of your current
          period.
        </p>
        <p>
          After termination we delete your stored data as described in the{" "}
          <Link className="text-white underline" href="/privacy">
            privacy policy
          </Link>
          , except records we must keep for billing, tax, or legal reasons, which Polar retains
          as merchant of record.
        </p>
      </Section>

      <Section title="Warranties">
        <p>
          <Term>
            The service is provided &quot;as is&quot; and &quot;as available&quot;, without
            warranties of any kind, whether express, implied, or statutory - including any
            implied warranty of merchantability, fitness for a particular purpose, title, or
            non-infringement.
          </Term>{" "}
          We do not warrant that the service will be uninterrupted, timely, secure, or
          error-free, that defects will be corrected, or that any result will be achieved.
        </p>
        <p>
          Some jurisdictions do not allow the exclusion of implied warranties, so parts of this
          section may not apply to you, and nothing here affects consumer rights that your local
          law makes non-excludable.
        </p>
      </Section>

      <Section title="Liability we never limit">
        <p>
          Nothing in these terms excludes or limits our liability for death or personal injury
          caused by our negligence, for fraud or fraudulent misrepresentation, for wilful
          misconduct or gross negligence, or for any other liability that the law does not
          permit us to exclude or limit. If any other provision of these terms would conflict
          with this one, this one wins.
        </p>
      </Section>

      <Section title="Limits on our liability">
        <p>
          Subject always to the section above, our total aggregate liability for all claims
          arising out of or relating to the service or these terms - whether in contract, tort
          (including negligence), statute or otherwise - will not exceed the greater of (a) the
          fees you paid us in the twelve months before the event giving rise to the claim, or
          (b) one hundred US dollars (US$100).
        </p>
        <p>
          Separately, and to the extent the law allows, we are not liable for indirect,
          incidental, special, consequential or punitive damages, nor for lost profits, lost
          revenue, lost or corrupted data, lost search rankings or traffic, loss of goodwill, or
          the cost of substitute services - even if we were told such damages were possible and
          even if a limited remedy fails of its essential purpose.
        </p>
        <p>
          Each of the two paragraphs above stands on its own. If one is held unenforceable, the
          other continues to apply.
        </p>
        <p>
          These limits reflect a deliberate allocation of risk in exchange for the price
          charged, and the service would not be offered at this price without them.
        </p>
      </Section>

      <Section title="Indemnity">
        <p>
          You will defend and indemnify us against third-party claims, and the reasonable legal
          costs and any award or settlement arising from them, to the extent they arise out of:
          content you published or caused to be published using the service; your breach of
          these terms or of the acceptable-use rules; your use of a site, repository, or account
          you were not authorised to use; or your infringement of anyone&apos;s intellectual
          property or other rights.
        </p>
        <p>
          We will tell you promptly about any such claim, give you control of its defence and
          settlement (except that you may not settle in a way that admits fault on our behalf or
          imposes an obligation on us without our consent, which we will not unreasonably
          withhold), and give you reasonable cooperation at your expense. This obligation does
          not apply to the extent the claim arises from our own breach, and it does not apply at
          all if you are a consumer and your local law does not permit it.
        </p>
      </Section>

      <Section title="Force majeure">
        <p>
          Neither of us is liable for a failure or delay caused by something beyond our
          reasonable control - including outages at hosting, payment, or API providers, network
          failures, cyberattacks, acts of government, war, or natural disaster. If such an event
          prevents us from providing the service for a prolonged period, either of us may
          terminate and we will refund fees paid for the period not delivered.
        </p>
      </Section>

      <Section title="Changes to these terms">
        <p>
          We may update these terms. For material changes we will give you at least 30
          days&apos; notice by email or in the product before they take effect, and the new
          terms apply from your next renewal after that. If you do not accept them, cancel
          before they take effect; continuing to use the service afterwards means you accept
          them. Non-material changes - fixing a typo, clarifying wording, naming a new
          subprocessor - take effect when posted. Every version is dated, and because the site
          is open source the full history of this page is public.
        </p>
      </Section>

      <Section title="Governing law and disputes">
        <p>
          These terms are governed by the laws of Israel, and the competent courts of Tel
          Aviv-Jaffa have exclusive jurisdiction. <Term>If you are a consumer</Term>, this does
          not deprive you of the protection of mandatory provisions of the law of the country
          where you live, or of your right to bring proceedings in your local courts.
        </p>
        <p>
          Before starting formal proceedings, please email {CONTACT} with a description of the
          problem and what you would like us to do. Most things are cheaper and faster to fix
          that way, and we commit to responding within 30 days.
        </p>
      </Section>

      <Section title="Everything else">
        <p>
          <Term>Severability.</Term> If any provision is held invalid or unenforceable, it is
          limited or removed to the minimum extent necessary and the rest of these terms remain
          in force.
        </p>
        <p>
          <Term>No waiver.</Term> If we do not enforce a provision, that is not a waiver of it
          or of our right to enforce it later.
        </p>
        <p>
          <Term>Assignment.</Term> You may not assign or transfer these terms without our
          written consent. We may assign them to a successor in connection with a merger,
          acquisition, or sale of the business, on notice to you.
        </p>
        <p>
          <Term>Notices.</Term> We will send notices to the email address on your account -
          keep it current. You can reach us at {CONTACT}.
        </p>
        <p>
          <Term>Export and sanctions.</Term> You confirm that you are not located in, and not
          acting on behalf of anyone in, a country or on a list subject to applicable trade
          sanctions or export restrictions.
        </p>
        <p>
          <Term>Entire agreement.</Term> These terms, together with the privacy policy and any
          data processing agreement between us, are the whole agreement about the hosted
          service and replace anything said before. Nothing here excludes liability for fraud.
        </p>
        <p>
          <Term>Survival.</Term> The sections on your content and our service, AI-generated
          content, warranties, liability, indemnity, governing law, and this section survive
          termination.
        </p>
        <p>
          <Term>No agency.</Term> These terms create no partnership, employment, or agency
          relationship between us, and give no rights to anyone who is not a party to them.
        </p>
      </Section>

      <Section title="Contact">
        <p>
          Questions about these terms: {CONTACT}. Questions about data:{" "}
          <Link className="text-white underline" href="/privacy">
            privacy policy
          </Link>{" "}
          and{" "}
          <Link className="text-white underline" href="/subprocessors">
            subprocessors
          </Link>
          .
        </p>
      </Section>

      <p className="text-sm text-neutral-500">
        <Link className="underline" href="/">
          Back to dispatchseo.com
        </Link>
      </p>
    </main>
  );
}
